package main

//go:generate genmsg msg actionlib/TestAction
//go:generate genmsg msg actionlib/TestActionFeedback
//go:generate genmsg msg actionlib/TestActionGoal
//go:generate genmsg msg actionlib/TestActionResult
//go:generate genmsg msg actionlib/TestFeedback
//go:generate genmsg msg actionlib/TestGoal
//go:generate genmsg msg actionlib/TestRequestAction
//go:generate genmsg msg actionlib/TestRequestActionFeedback
//go:generate genmsg msg actionlib/TestRequestActionGoal
//go:generate genmsg msg actionlib/TestRequestActionResult
//go:generate genmsg msg actionlib/TestRequestFeedback
//go:generate genmsg msg actionlib/TestRequestGoal
//go:generate genmsg msg actionlib/TestRequestResult
//go:generate genmsg msg actionlib/TestResult
//go:generate genmsg msg actionlib/TwoIntsAction
//go:generate genmsg msg actionlib/TwoIntsActionFeedback
//go:generate genmsg msg actionlib/TwoIntsActionGoal
//go:generate genmsg msg actionlib/TwoIntsActionResult
//go:generate genmsg msg actionlib/TwoIntsFeedback
//go:generate genmsg msg actionlib/TwoIntsGoal
//go:generate genmsg msg actionlib/TwoIntsResult
//go:generate genmsg msg actionlib_msgs/GoalID
//go:generate genmsg msg actionlib_msgs/GoalStatus
//go:generate genmsg msg actionlib_msgs/GoalStatusArray
//go:generate genmsg msg actionlib_tutorials/AveragingAction
//go:generate genmsg msg actionlib_tutorials/AveragingActionFeedback
//go:generate genmsg msg actionlib_tutorials/AveragingActionGoal
//go:generate genmsg msg actionlib_tutorials/AveragingActionResult
//go:generate genmsg msg actionlib_tutorials/AveragingFeedback
//go:generate genmsg msg actionlib_tutorials/AveragingGoal
//go:generate genmsg msg actionlib_tutorials/AveragingResult
//go:generate genmsg msg actionlib_tutorials/FibonacciAction
//go:generate genmsg msg actionlib_tutorials/FibonacciActionFeedback
//go:generate genmsg msg actionlib_tutorials/FibonacciActionGoal
//go:generate genmsg msg actionlib_tutorials/FibonacciActionResult
//go:generate genmsg msg actionlib_tutorials/FibonacciFeedback
//go:generate genmsg msg actionlib_tutorials/FibonacciGoal
//go:generate genmsg msg actionlib_tutorials/FibonacciResult
//go:generate genmsg msg diagnostic_msgs/DiagnosticArray
//go:generate genmsg msg diagnostic_msgs/DiagnosticStatus
//go:generate genmsg msg diagnostic_msgs/KeyValue
//go:generate genmsg msg geometry_msgs/Accel
//go:generate genmsg msg geometry_msgs/AccelStamped
//go:generate genmsg msg geometry_msgs/AccelWithCovariance
//go:generate genmsg msg geometry_msgs/AccelWithCovarianceStamped
//go:generate genmsg msg geometry_msgs/Inertia
//go:generate genmsg msg geometry_msgs/InertiaStamped
//go:generate genmsg msg geometry_msgs/Point
//go:generate genmsg msg geometry_msgs/Point32
//go:generate genmsg msg geometry_msgs/PointStamped
//go:generate genmsg msg geometry_msgs/Polygon
//go:generate genmsg msg geometry_msgs/PolygonStamped
//go:generate genmsg msg geometry_msgs/Pose
//go:generate genmsg msg geometry_msgs/Pose2D
//go:generate genmsg msg geometry_msgs/PoseArray
//go:generate genmsg msg geometry_msgs/PoseStamped
//go:generate genmsg msg geometry_msgs/PoseWithCovariance
//go:generate genmsg msg geometry_msgs/PoseWithCovarianceStamped
//go:generate genmsg msg geometry_msgs/Quaternion
//go:generate genmsg msg geometry_msgs/QuaternionStamped
//go:generate genmsg msg geometry_msgs/Transform
//go:generate genmsg msg geometry_msgs/TransformStamped
//go:generate genmsg msg geometry_msgs/Twist
//go:generate genmsg msg geometry_msgs/TwistStamped
//go:generate genmsg msg geometry_msgs/TwistWithCovariance
//go:generate genmsg msg geometry_msgs/TwistWithCovarianceStamped
//go:generate genmsg msg geometry_msgs/Vector3
//go:generate genmsg msg geometry_msgs/Vector3Stamped
//go:generate genmsg msg geometry_msgs/Wrench
//go:generate genmsg msg geometry_msgs/WrenchStamped
//go:generate genmsg msg nav_msgs/GetMapAction
//go:generate genmsg msg nav_msgs/GetMapActionFeedback
//go:generate genmsg msg nav_msgs/GetMapActionGoal
//go:generate genmsg msg nav_msgs/GetMapActionResult
//go:generate genmsg msg nav_msgs/GetMapFeedback
//go:generate genmsg msg nav_msgs/GetMapGoal
//go:generate genmsg msg nav_msgs/GetMapResult
//go:generate genmsg msg nav_msgs/GridCells
//go:generate genmsg msg nav_msgs/MapMetaData
//go:generate genmsg msg nav_msgs/OccupancyGrid
//go:generate genmsg msg nav_msgs/Odometry
//go:generate genmsg msg nav_msgs/Path
//go:generate genmsg msg rosapi/TypeDef
//go:generate genmsg msg roscpp/Logger
//go:generate genmsg msg rosgraph_msgs/Clock
//go:generate genmsg msg rosgraph_msgs/Log
//go:generate genmsg msg rosgraph_msgs/TopicStatistics
//go:generate genmsg msg sensor_msgs/BatteryState
//go:generate genmsg msg sensor_msgs/CameraInfo
//go:generate genmsg msg sensor_msgs/ChannelFloat32
//go:generate genmsg msg sensor_msgs/CompressedImage
//go:generate genmsg msg sensor_msgs/FluidPressure
//go:generate genmsg msg sensor_msgs/Illuminance
//go:generate genmsg msg sensor_msgs/Image
//go:generate genmsg msg sensor_msgs/Imu
//go:generate genmsg msg sensor_msgs/JointState
//go:generate genmsg msg sensor_msgs/Joy
//go:generate genmsg msg sensor_msgs/JoyFeedback
//go:generate genmsg msg sensor_msgs/JoyFeedbackArray
//go:generate genmsg msg sensor_msgs/LaserEcho
//go:generate genmsg msg sensor_msgs/LaserScan
//go:generate genmsg msg sensor_msgs/MagneticField
//go:generate genmsg msg sensor_msgs/MultiDOFJointState
//go:generate genmsg msg sensor_msgs/MultiEchoLaserScan
//go:generate genmsg msg sensor_msgs/NavSatFix
//go:generate genmsg msg sensor_msgs/NavSatStatus
//go:generate genmsg msg sensor_msgs/PointCloud
//go:generate genmsg msg sensor_msgs/PointCloud2
//go:generate genmsg msg sensor_msgs/PointField
//go:generate genmsg msg sensor_msgs/Range
//go:generate genmsg msg sensor_msgs/RegionOfInterest
//go:generate genmsg msg sensor_msgs/RelativeHumidity
//go:generate genmsg msg sensor_msgs/Temperature
//go:generate genmsg msg sensor_msgs/TimeReference
//go:generate genmsg msg shape_msgs/Mesh
//go:generate genmsg msg shape_msgs/MeshTriangle
//go:generate genmsg msg shape_msgs/Plane
//go:generate genmsg msg shape_msgs/SolidPrimitive
//go:generate genmsg msg std_msgs/Bool
//go:generate genmsg msg std_msgs/Byte
//go:generate genmsg msg std_msgs/ByteMultiArray
//go:generate genmsg msg std_msgs/Char
//go:generate genmsg msg std_msgs/ColorRGBA
//go:generate genmsg msg std_msgs/Duration
//go:generate genmsg msg std_msgs/Empty
//go:generate genmsg msg std_msgs/Float32
//go:generate genmsg msg std_msgs/Float32MultiArray
//go:generate genmsg msg std_msgs/Float64
//go:generate genmsg msg std_msgs/Float64MultiArray
//go:generate genmsg msg std_msgs/Header
//go:generate genmsg msg std_msgs/Int16
//go:generate genmsg msg std_msgs/Int16MultiArray
//go:generate genmsg msg std_msgs/Int32
//go:generate genmsg msg std_msgs/Int32MultiArray
//go:generate genmsg msg std_msgs/Int64
//go:generate genmsg msg std_msgs/Int64MultiArray
//go:generate genmsg msg std_msgs/Int8
//go:generate genmsg msg std_msgs/Int8MultiArray
//go:generate genmsg msg std_msgs/MultiArrayDimension
//go:generate genmsg msg std_msgs/MultiArrayLayout
//go:generate genmsg msg std_msgs/String
//go:generate genmsg msg std_msgs/Time
//go:generate genmsg msg std_msgs/UInt16
//go:generate genmsg msg std_msgs/UInt16MultiArray
//go:generate genmsg msg std_msgs/UInt32
//go:generate genmsg msg std_msgs/UInt32MultiArray
//go:generate genmsg msg std_msgs/UInt64
//go:generate genmsg msg std_msgs/UInt64MultiArray
//go:generate genmsg msg std_msgs/UInt8
//go:generate genmsg msg std_msgs/UInt8MultiArray
//go:generate genmsg msg tf/tfMessage
//go:generate genmsg msg tf2_msgs/LookupTransformAction
//go:generate genmsg msg tf2_msgs/LookupTransformActionFeedback
//go:generate genmsg msg tf2_msgs/LookupTransformActionGoal
//go:generate genmsg msg tf2_msgs/LookupTransformActionResult
//go:generate genmsg msg tf2_msgs/LookupTransformFeedback
//go:generate genmsg msg tf2_msgs/LookupTransformGoal
//go:generate genmsg msg tf2_msgs/LookupTransformResult
//go:generate genmsg msg tf2_msgs/TF2Error
//go:generate genmsg msg tf2_msgs/TFMessage
//go:generate genmsg msg trajectory_msgs/JointTrajectory
//go:generate genmsg msg trajectory_msgs/JointTrajectoryPoint
//go:generate genmsg msg trajectory_msgs/MultiDOFJointTrajectory
//go:generate genmsg msg trajectory_msgs/MultiDOFJointTrajectoryPoint
//go:generate genmsg msg vision_msgs/BoundingBox2D
//go:generate genmsg msg vision_msgs/BoundingBox3D
//go:generate genmsg msg vision_msgs/Classification2D
//go:generate genmsg msg vision_msgs/Classification3D
//go:generate genmsg msg vision_msgs/Detection2D
//go:generate genmsg msg vision_msgs/Detection2DArray
//go:generate genmsg msg vision_msgs/Detection3D
//go:generate genmsg msg vision_msgs/Detection3DArray
//go:generate genmsg msg vision_msgs/ObjectHypothesis
//go:generate genmsg msg vision_msgs/ObjectHypothesisWithPose
//go:generate genmsg msg vision_msgs/VisionInfo
//go:generate genmsg msg visualization_msgs/ImageMarker
//go:generate genmsg msg visualization_msgs/InteractiveMarker
//go:generate genmsg msg visualization_msgs/InteractiveMarkerControl
//go:generate genmsg msg visualization_msgs/InteractiveMarkerFeedback
//go:generate genmsg msg visualization_msgs/InteractiveMarkerInit
//go:generate genmsg msg visualization_msgs/InteractiveMarkerPose
//go:generate genmsg msg visualization_msgs/InteractiveMarkerUpdate
//go:generate genmsg msg visualization_msgs/Marker
//go:generate genmsg msg visualization_msgs/MarkerArray
//go:generate genmsg msg visualization_msgs/MenuEntry
//go:generate genmsg msg actionlib/TestAction
//go:generate genmsg msg actionlib/TestActionFeedback
//go:generate genmsg msg actionlib/TestActionGoal
//go:generate genmsg msg actionlib/TestActionResult
//go:generate genmsg msg actionlib/TestFeedback
//go:generate genmsg msg actionlib/TestGoal
//go:generate genmsg msg actionlib/TestRequestAction
//go:generate genmsg msg actionlib/TestRequestActionFeedback
//go:generate genmsg msg actionlib/TestRequestActionGoal
//go:generate genmsg msg actionlib/TestRequestActionResult
//go:generate genmsg msg actionlib/TestRequestFeedback
//go:generate genmsg msg actionlib/TestRequestGoal
//go:generate genmsg msg actionlib/TestRequestResult
//go:generate genmsg msg actionlib/TestResult
//go:generate genmsg msg actionlib/TwoIntsAction
//go:generate genmsg msg actionlib/TwoIntsActionFeedback
//go:generate genmsg msg actionlib/TwoIntsActionGoal
//go:generate genmsg msg actionlib/TwoIntsActionResult
//go:generate genmsg msg actionlib/TwoIntsFeedback
//go:generate genmsg msg actionlib/TwoIntsGoal
//go:generate genmsg msg actionlib/TwoIntsResult
//go:generate genmsg msg actionlib_msgs/GoalID
//go:generate genmsg msg actionlib_msgs/GoalStatus
//go:generate genmsg msg actionlib_msgs/GoalStatusArray
//go:generate genmsg msg actionlib_tutorials/AveragingAction
//go:generate genmsg msg actionlib_tutorials/AveragingActionFeedback
//go:generate genmsg msg actionlib_tutorials/AveragingActionGoal
//go:generate genmsg msg actionlib_tutorials/AveragingActionResult
//go:generate genmsg msg actionlib_tutorials/AveragingFeedback
//go:generate genmsg msg actionlib_tutorials/AveragingGoal
//go:generate genmsg msg actionlib_tutorials/AveragingResult
//go:generate genmsg msg actionlib_tutorials/FibonacciAction
//go:generate genmsg msg actionlib_tutorials/FibonacciActionFeedback
//go:generate genmsg msg actionlib_tutorials/FibonacciActionGoal
//go:generate genmsg msg actionlib_tutorials/FibonacciActionResult
//go:generate genmsg msg actionlib_tutorials/FibonacciFeedback
//go:generate genmsg msg actionlib_tutorials/FibonacciGoal
//go:generate genmsg msg actionlib_tutorials/FibonacciResult
//go:generate genmsg msg bond/Constants
//go:generate genmsg msg bond/Status
//go:generate genmsg msg calibration_msgs/CalibrationPattern
//go:generate genmsg msg calibration_msgs/CameraMeasurement
//go:generate genmsg msg calibration_msgs/ChainMeasurement
//go:generate genmsg msg calibration_msgs/DenseLaserObjectFeatures
//go:generate genmsg msg calibration_msgs/DenseLaserPoint
//go:generate genmsg msg calibration_msgs/DenseLaserSnapshot
//go:generate genmsg msg calibration_msgs/Interval
//go:generate genmsg msg calibration_msgs/IntervalStamped
//go:generate genmsg msg calibration_msgs/IntervalStatus
//go:generate genmsg msg calibration_msgs/JointStateCalibrationPattern
//go:generate genmsg msg calibration_msgs/LaserMeasurement
//go:generate genmsg msg calibration_msgs/RobotMeasurement
//go:generate genmsg msg control_msgs/FollowJointTrajectoryAction
//go:generate genmsg msg control_msgs/FollowJointTrajectoryActionFeedback
//go:generate genmsg msg control_msgs/FollowJointTrajectoryActionGoal
//go:generate genmsg msg control_msgs/FollowJointTrajectoryActionResult
//go:generate genmsg msg control_msgs/FollowJointTrajectoryFeedback
//go:generate genmsg msg control_msgs/FollowJointTrajectoryGoal
//go:generate genmsg msg control_msgs/FollowJointTrajectoryResult
//go:generate genmsg msg control_msgs/GripperCommand
//go:generate genmsg msg control_msgs/GripperCommandAction
//go:generate genmsg msg control_msgs/GripperCommandActionFeedback
//go:generate genmsg msg control_msgs/GripperCommandActionGoal
//go:generate genmsg msg control_msgs/GripperCommandActionResult
//go:generate genmsg msg control_msgs/GripperCommandFeedback
//go:generate genmsg msg control_msgs/GripperCommandGoal
//go:generate genmsg msg control_msgs/GripperCommandResult
//go:generate genmsg msg control_msgs/JointControllerState
//go:generate genmsg msg control_msgs/JointTolerance
//go:generate genmsg msg control_msgs/JointTrajectoryAction
//go:generate genmsg msg control_msgs/JointTrajectoryActionFeedback
//go:generate genmsg msg control_msgs/JointTrajectoryActionGoal
//go:generate genmsg msg control_msgs/JointTrajectoryActionResult
//go:generate genmsg msg control_msgs/JointTrajectoryControllerState
//go:generate genmsg msg control_msgs/JointTrajectoryFeedback
//go:generate genmsg msg control_msgs/JointTrajectoryGoal
//go:generate genmsg msg control_msgs/JointTrajectoryResult
//go:generate genmsg msg control_msgs/PidState
//go:generate genmsg msg control_msgs/PointHeadAction
//go:generate genmsg msg control_msgs/PointHeadActionFeedback
//go:generate genmsg msg control_msgs/PointHeadActionGoal
//go:generate genmsg msg control_msgs/PointHeadActionResult
//go:generate genmsg msg control_msgs/PointHeadFeedback
//go:generate genmsg msg control_msgs/PointHeadGoal
//go:generate genmsg msg control_msgs/PointHeadResult
//go:generate genmsg msg control_msgs/SingleJointPositionAction
//go:generate genmsg msg control_msgs/SingleJointPositionActionFeedback
//go:generate genmsg msg control_msgs/SingleJointPositionActionGoal
//go:generate genmsg msg control_msgs/SingleJointPositionActionResult
//go:generate genmsg msg control_msgs/SingleJointPositionFeedback
//go:generate genmsg msg control_msgs/SingleJointPositionGoal
//go:generate genmsg msg control_msgs/SingleJointPositionResult
//go:generate genmsg msg dynamic_reconfigure/BoolParameter
//go:generate genmsg msg dynamic_reconfigure/Config
//go:generate genmsg msg dynamic_reconfigure/ConfigDescription
//go:generate genmsg msg dynamic_reconfigure/DoubleParameter
//go:generate genmsg msg dynamic_reconfigure/Group
//go:generate genmsg msg dynamic_reconfigure/GroupState
//go:generate genmsg msg dynamic_reconfigure/IntParameter
//go:generate genmsg msg dynamic_reconfigure/ParamDescription
//go:generate genmsg msg dynamic_reconfigure/SensorLevels
//go:generate genmsg msg dynamic_reconfigure/StrParameter
//go:generate genmsg msg gazebo_msgs/ContactState
//go:generate genmsg msg gazebo_msgs/ContactsState
//go:generate genmsg msg gazebo_msgs/LinkState
//go:generate genmsg msg gazebo_msgs/LinkStates
//go:generate genmsg msg gazebo_msgs/ModelState
//go:generate genmsg msg gazebo_msgs/ModelStates
//go:generate genmsg msg gazebo_msgs/ODEJointProperties
//go:generate genmsg msg gazebo_msgs/ODEPhysics
//go:generate genmsg msg gazebo_msgs/WorldState
//go:generate genmsg msg geometry_msgs/Accel
//go:generate genmsg msg geometry_msgs/AccelStamped
//go:generate genmsg msg geometry_msgs/AccelWithCovariance
//go:generate genmsg msg geometry_msgs/AccelWithCovarianceStamped
//go:generate genmsg msg geometry_msgs/Inertia
//go:generate genmsg msg geometry_msgs/InertiaStamped
//go:generate genmsg msg geometry_msgs/Point
//go:generate genmsg msg geometry_msgs/Point32
//go:generate genmsg msg geometry_msgs/PointStamped
//go:generate genmsg msg geometry_msgs/Polygon
//go:generate genmsg msg geometry_msgs/PolygonStamped
//go:generate genmsg msg geometry_msgs/Pose
//go:generate genmsg msg geometry_msgs/Pose2D
//go:generate genmsg msg geometry_msgs/PoseArray
//go:generate genmsg msg geometry_msgs/PoseStamped
//go:generate genmsg msg geometry_msgs/PoseWithCovariance
//go:generate genmsg msg geometry_msgs/PoseWithCovarianceStamped
//go:generate genmsg msg geometry_msgs/Quaternion
//go:generate genmsg msg geometry_msgs/QuaternionStamped
//go:generate genmsg msg geometry_msgs/Transform
//go:generate genmsg msg geometry_msgs/TransformStamped
//go:generate genmsg msg geometry_msgs/Twist
//go:generate genmsg msg geometry_msgs/TwistStamped
//go:generate genmsg msg geometry_msgs/TwistWithCovariance
//go:generate genmsg msg geometry_msgs/TwistWithCovarianceStamped
//go:generate genmsg msg geometry_msgs/Vector3
//go:generate genmsg msg geometry_msgs/Vector3Stamped
//go:generate genmsg msg geometry_msgs/Wrench
//go:generate genmsg msg geometry_msgs/WrenchStamped
//go:generate genmsg msg graph_msgs/Edges
//go:generate genmsg msg graph_msgs/GeometryGraph
//go:generate genmsg msg moveit_msgs/AllowedCollisionEntry
//go:generate genmsg msg moveit_msgs/AllowedCollisionMatrix
//go:generate genmsg msg moveit_msgs/AttachedCollisionObject
//go:generate genmsg msg moveit_msgs/BoundingVolume
//go:generate genmsg msg moveit_msgs/CollisionObject
//go:generate genmsg msg moveit_msgs/ConstraintEvalResult
//go:generate genmsg msg moveit_msgs/Constraints
//go:generate genmsg msg moveit_msgs/ContactInformation
//go:generate genmsg msg moveit_msgs/CostSource
//go:generate genmsg msg moveit_msgs/DisplayRobotState
//go:generate genmsg msg moveit_msgs/DisplayTrajectory
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryAction
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryActionFeedback
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryActionGoal
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryActionResult
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryFeedback
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryGoal
//go:generate genmsg msg moveit_msgs/ExecuteTrajectoryResult
//go:generate genmsg msg moveit_msgs/Grasp
//go:generate genmsg msg moveit_msgs/GripperTranslation
//go:generate genmsg msg moveit_msgs/JointConstraint
//go:generate genmsg msg moveit_msgs/JointLimits
//go:generate genmsg msg moveit_msgs/KinematicSolverInfo
//go:generate genmsg msg moveit_msgs/LinkPadding
//go:generate genmsg msg moveit_msgs/LinkScale
//go:generate genmsg msg moveit_msgs/MotionPlanDetailedResponse
//go:generate genmsg msg moveit_msgs/MotionPlanRequest
//go:generate genmsg msg moveit_msgs/MotionPlanResponse
//go:generate genmsg msg moveit_msgs/MoveGroupAction
//go:generate genmsg msg moveit_msgs/MoveGroupActionFeedback
//go:generate genmsg msg moveit_msgs/MoveGroupActionGoal
//go:generate genmsg msg moveit_msgs/MoveGroupActionResult
//go:generate genmsg msg moveit_msgs/MoveGroupFeedback
//go:generate genmsg msg moveit_msgs/MoveGroupGoal
//go:generate genmsg msg moveit_msgs/MoveGroupResult
//go:generate genmsg msg moveit_msgs/MoveItErrorCodes
//go:generate genmsg msg moveit_msgs/ObjectColor
//go:generate genmsg msg moveit_msgs/OrientationConstraint
//go:generate genmsg msg moveit_msgs/OrientedBoundingBox
//go:generate genmsg msg moveit_msgs/PickupAction
//go:generate genmsg msg moveit_msgs/PickupActionFeedback
//go:generate genmsg msg moveit_msgs/PickupActionGoal
//go:generate genmsg msg moveit_msgs/PickupActionResult
//go:generate genmsg msg moveit_msgs/PickupFeedback
//go:generate genmsg msg moveit_msgs/PickupGoal
//go:generate genmsg msg moveit_msgs/PickupResult
//go:generate genmsg msg moveit_msgs/PlaceAction
//go:generate genmsg msg moveit_msgs/PlaceActionFeedback
//go:generate genmsg msg moveit_msgs/PlaceActionGoal
//go:generate genmsg msg moveit_msgs/PlaceActionResult
//go:generate genmsg msg moveit_msgs/PlaceFeedback
//go:generate genmsg msg moveit_msgs/PlaceGoal
//go:generate genmsg msg moveit_msgs/PlaceLocation
//go:generate genmsg msg moveit_msgs/PlaceResult
//go:generate genmsg msg moveit_msgs/PlannerInterfaceDescription
//go:generate genmsg msg moveit_msgs/PlannerParams
//go:generate genmsg msg moveit_msgs/PlanningOptions
//go:generate genmsg msg moveit_msgs/PlanningScene
//go:generate genmsg msg moveit_msgs/PlanningSceneComponents
//go:generate genmsg msg moveit_msgs/PlanningSceneWorld
//go:generate genmsg msg moveit_msgs/PositionConstraint
//go:generate genmsg msg moveit_msgs/PositionIKRequest
//go:generate genmsg msg moveit_msgs/RobotState
//go:generate genmsg msg moveit_msgs/RobotTrajectory
//go:generate genmsg msg moveit_msgs/TrajectoryConstraints
//go:generate genmsg msg moveit_msgs/VisibilityConstraint
//go:generate genmsg msg moveit_msgs/WorkspaceParameters
//go:generate genmsg msg nav_msgs/GetMapAction
//go:generate genmsg msg nav_msgs/GetMapActionFeedback
//go:generate genmsg msg nav_msgs/GetMapActionGoal
//go:generate genmsg msg nav_msgs/GetMapActionResult
//go:generate genmsg msg nav_msgs/GetMapFeedback
//go:generate genmsg msg nav_msgs/GetMapGoal
//go:generate genmsg msg nav_msgs/GetMapResult
//go:generate genmsg msg nav_msgs/GridCells
//go:generate genmsg msg nav_msgs/MapMetaData
//go:generate genmsg msg nav_msgs/OccupancyGrid
//go:generate genmsg msg nav_msgs/Odometry
//go:generate genmsg msg nav_msgs/Path
//go:generate genmsg msg pcl_msgs/ModelCoefficients
//go:generate genmsg msg pcl_msgs/PointIndices
//go:generate genmsg msg pcl_msgs/PolygonMesh
//go:generate genmsg msg pcl_msgs/Vertices
//go:generate genmsg msg sensor_msgs/CameraInfo
//go:generate genmsg msg sensor_msgs/ChannelFloat32
//go:generate genmsg msg sensor_msgs/CompressedImage
//go:generate genmsg msg sensor_msgs/FluidPressure
//go:generate genmsg msg sensor_msgs/Illuminance
//go:generate genmsg msg sensor_msgs/Image
//go:generate genmsg msg sensor_msgs/Imu
//go:generate genmsg msg sensor_msgs/JointState
//go:generate genmsg msg sensor_msgs/Joy
//go:generate genmsg msg sensor_msgs/JoyFeedback
//go:generate genmsg msg sensor_msgs/JoyFeedbackArray
//go:generate genmsg msg sensor_msgs/LaserEcho
//go:generate genmsg msg sensor_msgs/LaserScan
//go:generate genmsg msg sensor_msgs/MagneticField
//go:generate genmsg msg sensor_msgs/MultiDOFJointState
//go:generate genmsg msg sensor_msgs/MultiEchoLaserScan
//go:generate genmsg msg sensor_msgs/NavSatFix
//go:generate genmsg msg sensor_msgs/NavSatStatus
//go:generate genmsg msg sensor_msgs/PointCloud
//go:generate genmsg msg sensor_msgs/PointCloud2
//go:generate genmsg msg sensor_msgs/PointField
//go:generate genmsg msg sensor_msgs/Range
//go:generate genmsg msg sensor_msgs/RegionOfInterest
//go:generate genmsg msg sensor_msgs/RelativeHumidity
//go:generate genmsg msg sensor_msgs/Temperature
//go:generate genmsg msg sensor_msgs/TimeReference
//go:generate genmsg msg shape_msgs/Mesh
//go:generate genmsg msg shape_msgs/MeshTriangle
//go:generate genmsg msg shape_msgs/Plane
//go:generate genmsg msg shape_msgs/SolidPrimitive
//go:generate genmsg msg std_msgs/Bool
//go:generate genmsg msg std_msgs/Byte
//go:generate genmsg msg std_msgs/ByteMultiArray
//go:generate genmsg msg std_msgs/Char
//go:generate genmsg msg std_msgs/ColorRGBA
//go:generate genmsg msg std_msgs/Duration
//go:generate genmsg msg std_msgs/Empty
//go:generate genmsg msg std_msgs/Float32
//go:generate genmsg msg std_msgs/Float32MultiArray
//go:generate genmsg msg std_msgs/Float64
//go:generate genmsg msg std_msgs/Float64MultiArray
//go:generate genmsg msg std_msgs/Header
//go:generate genmsg msg std_msgs/Int16
//go:generate genmsg msg std_msgs/Int16MultiArray
//go:generate genmsg msg std_msgs/Int32
//go:generate genmsg msg std_msgs/Int32MultiArray
//go:generate genmsg msg std_msgs/Int64
//go:generate genmsg msg std_msgs/Int64MultiArray
//go:generate genmsg msg std_msgs/Int8
//go:generate genmsg msg std_msgs/Int8MultiArray
//go:generate genmsg msg std_msgs/MultiArrayDimension
//go:generate genmsg msg std_msgs/MultiArrayLayout
//go:generate genmsg msg std_msgs/String
//go:generate genmsg msg std_msgs/Time
//go:generate genmsg msg std_msgs/UInt16
//go:generate genmsg msg std_msgs/UInt16MultiArray
//go:generate genmsg msg std_msgs/UInt32
//go:generate genmsg msg std_msgs/UInt32MultiArray
//go:generate genmsg msg std_msgs/UInt64
//go:generate genmsg msg std_msgs/UInt64MultiArray
//go:generate genmsg msg std_msgs/UInt8
//go:generate genmsg msg std_msgs/UInt8MultiArray
//go:generate genmsg msg tf/tfMessage
//go:generate genmsg msg tf2_msgs/LookupTransformAction
//go:generate genmsg msg tf2_msgs/LookupTransformActionFeedback
//go:generate genmsg msg tf2_msgs/LookupTransformActionGoal
//go:generate genmsg msg tf2_msgs/LookupTransformActionResult
//go:generate genmsg msg tf2_msgs/LookupTransformFeedback
//go:generate genmsg msg tf2_msgs/LookupTransformGoal
//go:generate genmsg msg tf2_msgs/LookupTransformResult
//go:generate genmsg msg tf2_msgs/TF2Error
//go:generate genmsg msg tf2_msgs/TFMessage
//go:generate genmsg msg trajectory_msgs/JointTrajectory
//go:generate genmsg msg trajectory_msgs/JointTrajectoryPoint
//go:generate genmsg msg trajectory_msgs/MultiDOFJointTrajectory
//go:generate genmsg msg trajectory_msgs/MultiDOFJointTrajectoryPoint
//go:generate genmsg msg visualization_msgs/ImageMarker
//go:generate genmsg msg visualization_msgs/InteractiveMarker
//go:generate genmsg msg visualization_msgs/InteractiveMarkerControl
//go:generate genmsg msg visualization_msgs/InteractiveMarkerFeedback
//go:generate genmsg msg visualization_msgs/InteractiveMarkerInit
//go:generate genmsg msg visualization_msgs/InteractiveMarkerPose
//go:generate genmsg msg visualization_msgs/InteractiveMarkerUpdate
//go:generate genmsg msg visualization_msgs/Marker
//go:generate genmsg msg visualization_msgs/MarkerArray
//go:generate genmsg msg visualization_msgs/MenuEntry

//go:generate genmsg srv std_srvs/Empty
//go:generate genmsg srv std_srvs/SetBool
//go:generate genmsg srv std_srvs/Trigger
